from pymol import editor, cmd
cmd.load("trunc_cap.pdb")
# select & remove all non A altlocs
cmd.remove( "not alt ''+A" )
# reset the PDB information
cmd.alter("all", "alt=''")
editor.attach_amino_acid("resi 53 and name N", "ace")
editor.attach_amino_acid("resi 56 and name C", "nme")
editor.attach_amino_acid("resi 71 and name N", "ace")
editor.attach_amino_acid("resi 88 and name C", "nme")
editor.attach_amino_acid("resi 94 and name N", "ace")
editor.attach_amino_acid("resi 101 and name C", "nme")
editor.attach_amino_acid("resi 105 and name N", "ace")
editor.attach_amino_acid("resi 114 and name C", "nme")
editor.attach_amino_acid("resi 120 and name N", "ace")
editor.attach_amino_acid("resi 128 and name C", "nme")
editor.attach_amino_acid("resi 135 and name N", "ace")
editor.attach_amino_acid("resi 153 and name C", "nme")
editor.attach_amino_acid("resi 169 and name N", "ace")
editor.attach_amino_acid("resi 169 and name C", "nme")
editor.attach_amino_acid("resi 183 and name N", "ace")
editor.attach_amino_acid("resi 208 and name C", "nme")
editor.attach_amino_acid("resi 223 and name N", "ace")
editor.attach_amino_acid("resi 224 and name C", "nme")
editor.attach_amino_acid("resi 227 and name N", "ace")
editor.attach_amino_acid("resi 227 and name C", "nme")
editor.attach_amino_acid("resi 250 and name N", "ace")
editor.attach_amino_acid("resi 250 and name C", "nme")
editor.attach_amino_acid("resi 253 and name N", "ace")
editor.attach_amino_acid("resi 253 and name C", "nme")
editor.attach_amino_acid("resi 259 and name N", "ace")
editor.attach_amino_acid("resi 259 and name C", "nme")
editor.attach_amino_acid("resi 330 and name N", "ace")
editor.attach_amino_acid("resi 331 and name C", "nme")
cmd.set("pdb_use_ter_records",0)
cmd.save("trunc_cap_pymol.pdb")
